# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3fb484bce0cf739d3e6996ea1108dd4a5883ed581a8414ccc877038b1d2de2a9103622b7c43b44f6ceb43e18689b77e0b96e1bd4317a9ab797f4d5bfdd985e4

test:
  secret_key_base: 67ae41b47deca8877133e098b9fd4fd04a04ab305d66d9a644062be7684beb98a624772c2f8d9305125c1c7d48e40d9d19b52c235b096bd50de029324f82a7e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
